user = "your_name"
serverAddr = "0.0.0.0"
serverPort = 7000

auth.method = "token"
auth.token = "12345678"

transport.protocol = "quic"
transport.heartbeatTimeout = 30
transport.poolCount = 10

webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"

[[proxies]]
name = "web01"
type = "http"
localIP = "127.0.0.1"
localPort = 8080
subdomain = "web01"
requestHeaders.set.x-from-where = "frp"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "192.168.31.100"
localPort = 22
remotePort = 0

[[proxies]]
name = "plugin_static_file"
type = "tcp"
remotePort = 0
[proxies.plugin]
type = "static_file"
localPath = "/tmp/files"
stripPrefix = "static"
httpUser = "abc"
httpPassword = "abc"
